# 标准权限配置文件
# 用于初始化和管理系统权限

standard_permissions:
  # 用户管理权限
  user:
    - code: "user:view"
      name: "查看用户"
      description: "查看用户列表和详情"
      action: "view"
      resource_type: "menu"
      status: true
    - code: "user:create"
      name: "创建用户"
      description: "创建新用户"
      action: "create"
      resource_type: "menu"
      status: true
    - code: "user:update"
      name: "编辑用户"
      description: "修改用户信息"
      action: "update"
      resource_type: "menu"
      status: true
    - code: "user:delete"
      name: "删除用户"
      description: "删除用户账号"
      action: "delete"
      resource_type: "menu"
      status: true
    - code: "user:export"
      name: "导出用户"
      description: "导出用户数据"
      action: "export"
      resource_type: "feature"
      status: true

  # 角色管理权限
  role:
    - code: "role:view"
      name: "查看角色"
      description: "查看角色列表和详情"
      action: "view"
      resource_type: "menu"
      status: true
    - code: "role:create"
      name: "创建角色"
      description: "创建新角色"
      action: "create"
      resource_type: "menu"
      status: true
    - code: "role:update"
      name: "编辑角色"
      description: "修改角色信息"
      action: "update"
      resource_type: "menu"
      status: true
    - code: "role:delete"
      name: "删除角色"
      description: "删除角色"
      action: "delete"
      resource_type: "menu"
      status: true
    - code: "role:assign"
      name: "分配角色"
      description: "为用户分配角色"
      action: "assign"
      resource_type: "feature"
      status: true

  # 菜单管理权限
  menu:
    - code: "menu:view"
      name: "查看菜单"
      description: "查看菜单列表"
      action: "view"
      resource_type: "menu"
      status: true
    - code: "menu:create"
      name: "创建菜单"
      description: "创建新菜单"
      action: "create"
      resource_type: "menu"
      status: true
    - code: "menu:update"
      name: "编辑菜单"
      description: "修改菜单信息"
      action: "update"
      resource_type: "menu"
      status: true
    - code: "menu:delete"
      name: "删除菜单"
      description: "删除菜单"
      action: "delete"
      resource_type: "menu"
      status: true

  # 权限管理
  permission:
    - code: "permission:view"
      name: "查看权限"
      description: "查看权限列表"
      action: "view"
      resource_type: "menu"
      status: true
    - code: "permission:assign"
      name: "分配权限"
      description: "为角色分配权限"
      action: "assign"
      resource_type: "feature"
      status: true

  # 租户管理权限
  tenant:
    - code: "tenant:view"
      name: "查看租户"
      description: "查看租户信息"
      action: "view"
      resource_type: "menu"
      status: true

# 自定义权限模块配置
custom_modules:
  # 支持扩展其他业务模块权限
  # 格式与standard_permissions相同

# 权限初始化设置
init_settings:
  # 默认租户ID
  default_tenant_id: 1
  
  # 是否启用自动权限发现（根据API路由自动生成权限）
  auto_discovery: false
  
  # 权限编码命名规范
  naming_convention:
    format: "{module}:{action}"
    allowed_actions: ["view", "create", "update", "delete", "export", "import", "assign"]
    
  # 是否允许运行时动态创建权限
  allow_dynamic_creation: true 