// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMenuPermissionM = "menu_permissions"

// MenuPermissionM mapped from table <menu_permissions>
type MenuPermissionM struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                                  // 主键ID
	TenantID     int64     `gorm:"column:tenant_id;not null;comment:租户ID" json:"tenant_id"`                                         // 租户ID
	MenuID       int64     `gorm:"column:menu_id;not null;uniqueIndex:idx_menu_permission;comment:菜单ID" json:"menu_id"`             // 菜单ID
	PermissionID int64     `gorm:"column:permission_id;not null;uniqueIndex:idx_menu_permission;comment:权限ID" json:"permission_id"` // 权限ID
	IsRequired   bool      `gorm:"column:is_required;not null;comment:是否为访问菜单的必需权限" json:"is_required"`                             // 是否为访问菜单的必需权限
	CreatedAt    time.Time `gorm:"column:created_at;not null;default:current_timestamp;comment:创建时间" json:"created_at"`             // 创建时间
	UpdatedAt    time.Time `gorm:"column:updated_at;not null;default:current_timestamp;comment:更新时间" json:"updated_at"`             // 更新时间
}

// TableName MenuPermissionM's table name
func (*MenuPermissionM) TableName() string {
	return TableNameMenuPermissionM
}
