// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNamePostM = "post"

// PostM mapped from table <post>
type PostM struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:博文主键ID" json:"id"`                        // 博文主键ID
	UserID    int64          `gorm:"column:user_id;not null;comment:用户ID（关联user表）" json:"user_id"`                            // 用户ID（关联user表）
	PostID    string         `gorm:"column:post_id;not null;uniqueIndex:idx_post_post_id;comment:博文唯一标识" json:"post_id"`      // 博文唯一标识
	Title     string         `gorm:"column:title;not null;comment:博文标题" json:"title"`                                         // 博文标题
	Content   string         `gorm:"column:content;not null;comment:博文内容" json:"content"`                                     // 博文内容
	CreatedAt time.Time      `gorm:"column:created_at;not null;default:current_timestamp;comment:博文创建时间" json:"created_at"`   // 博文创建时间
	UpdatedAt time.Time      `gorm:"column:updated_at;not null;default:current_timestamp;comment:博文最后修改时间" json:"updated_at"` // 博文最后修改时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;index;comment:软删除时间" json:"deleted_at"`                                 // 软删除时间
}

// TableName PostM's table name
func (*PostM) TableName() string {
	return TableNamePostM
}
