// Copyright 2024 孔令飞 <colin404@foxmail.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file. The original repo for
// this file is https://github.com/ashwinyue/one-auth. The professional
// version of this repository is https://github.com/onexstack/onex.

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"gorm.io/gorm"
	"time"
)

const TableNamePostM = "post"

// PostM mapped from table <post>
type PostM struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TenantID  int64          `gorm:"column:tenant_id;default:1;comment:租户 ID" json:"tenant_id"`                               // 租户 ID
	UserID    int64          `gorm:"column:user_id;not null;comment:用户ID" json:"user_id"`                                     // 用户ID
	PostID    string         `gorm:"column:post_id;not null;uniqueIndex:idx_post_post_id;comment:博文唯一 ID" json:"post_id"`     // 博文唯一 ID
	Title     string         `gorm:"column:title;not null;comment:博文标题" json:"title"`                                         // 博文标题
	Content   string         `gorm:"column:content;not null;comment:博文内容" json:"content"`                                     // 博文内容
	CreatedAt time.Time      `gorm:"column:created_at;not null;default:current_timestamp;comment:博文创建时间" json:"created_at"`   // 博文创建时间
	UpdatedAt time.Time      `gorm:"column:updated_at;not null;default:current_timestamp;comment:博文最后修改时间" json:"updated_at"` // 博文最后修改时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;index;comment:软删除时间" json:"deletedAt"`                                  // 软删除时间
}

// TableName PostM's table name
func (*PostM) TableName() string {
	return TableNamePostM
}
