// 菜单管理 API 定义

// Copyright 2024 孔令飞 <colin404@foxmail.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file. The original repo for
// this file is https://github.com/ashwinyue/one-auth. The professional
// version of this repository is https://github.com/onexstack/onex.

// Code generated by protoc-gen-defaults. DO NOT EDIT.

package v1

import (
	"google.golang.org/protobuf/types/known/durationpb"
	"google.golang.org/protobuf/types/known/timestamppb"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

var (
	_ *timestamppb.Timestamp
	_ *durationpb.Duration
	_ *wrapperspb.BoolValue
)

func (x *Menu) Default() {
}

func (x *CreateMenuRequest) Default() {
}

func (x *CreateMenuResponse) Default() {
}

func (x *UpdateMenuRequest) Default() {
}

func (x *UpdateMenuResponse) Default() {
}

func (x *DeleteMenuRequest) Default() {
}

func (x *DeleteMenuResponse) Default() {
}

func (x *GetMenuRequest) Default() {
}

func (x *GetMenuResponse) Default() {
}

func (x *GetUserMenusRequest) Default() {
}

func (x *GetUserMenusResponse) Default() {
}

func (x *ListMenusRequest) Default() {
}

func (x *ListMenusResponse) Default() {
}

func (x *GetMenuTreeRequest) Default() {
}

func (x *GetMenuTreeResponse) Default() {
}

func (x *MenuSortItem) Default() {
}

func (x *UpdateMenuSortRequest) Default() {
}

func (x *UpdateMenuSortResponse) Default() {
}

func (x *CopyMenuRequest) Default() {
}

func (x *CopyMenuResponse) Default() {
}

func (x *MoveMenuRequest) Default() {
}

func (x *MoveMenuResponse) Default() {
}
