// 管理员权限自动分配 API 定义

// Copyright 2024 孔令飞 <colin404@foxmail.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file. The original repo for
// this file is https://github.com/ashwinyue/one-auth. The professional
// version of this repository is https://github.com/onexstack/onex.

// Code generated by protoc-gen-defaults. DO NOT EDIT.

package v1

import (
	"google.golang.org/protobuf/types/known/durationpb"
	"google.golang.org/protobuf/types/known/timestamppb"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

var (
	_ *timestamppb.Timestamp
	_ *durationpb.Duration
	_ *wrapperspb.BoolValue
)

func (x *CreateMenuWithPermissionsRequest) Default() {
}

func (x *CreateMenuWithPermissionsResponse) Default() {
}

func (x *PreviewPermissionAssignmentRequest) Default() {
}

func (x *PreviewPermissionAssignmentResponse) Default() {
}

func (x *SyncAdminPermissionsRequest) Default() {
}

func (x *SyncAdminPermissionsResponse) Default() {
}

func (x *SyncDetail) Default() {
}

func (x *GetAutoAssignConfigRequest) Default() {
}

func (x *GetAutoAssignConfigResponse) Default() {
}

func (x *UpdateAutoAssignConfigRequest) Default() {
}

func (x *UpdateAutoAssignConfigResponse) Default() {
}

func (x *RoleInfo) Default() {
}

func (x *PermissionRule) Default() {
}

func (x *GetAdminMissingPermissionsRequest) Default() {
}

func (x *GetAdminMissingPermissionsResponse) Default() {
}

func (x *MissingPermission) Default() {
}
