// 角色管理 API 定义

// Copyright 2024 孔令飞 <colin404@foxmail.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file. The original repo for
// this file is https://github.com/ashwinyue/one-auth. The professional
// version of this repository is https://github.com/onexstack/onex.

// Code generated by protoc-gen-defaults. DO NOT EDIT.

package v1

import (
	"google.golang.org/protobuf/types/known/durationpb"
	"google.golang.org/protobuf/types/known/timestamppb"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

var (
	_ *timestamppb.Timestamp
	_ *durationpb.Duration
	_ *wrapperspb.BoolValue
)

func (x *Role) Default() {
}

func (x *ListRolesRequest) Default() {
}

func (x *ListRolesResponse) Default() {
}

func (x *GetRoleRequest) Default() {
}

func (x *GetRoleResponse) Default() {
}

func (x *GetRolePermissionsRequest) Default() {
}

func (x *GetRolePermissionsResponse) Default() {
}

func (x *AssignRolePermissionsRequest) Default() {
}

func (x *AssignRolePermissionsResponse) Default() {
}

func (x *GetUserRolesRequest) Default() {
}

func (x *GetUserRolesResponse) Default() {
}

func (x *AssignUserRolesRequest) Default() {
}

func (x *AssignUserRolesResponse) Default() {
}

func (x *CreateRoleRequest) Default() {
}

func (x *CreateRoleResponse) Default() {
}

func (x *UpdateRoleRequest) Default() {
}

func (x *UpdateRoleResponse) Default() {
}

func (x *DeleteRoleRequest) Default() {
}

func (x *DeleteRoleResponse) Default() {
}

func (x *CheckDeleteRoleRequest) Default() {
}

func (x *CheckDeleteRoleResponse) Default() {
}

func (x *GetRoleMenusRequest) Default() {
}

func (x *GetRoleMenusResponse) Default() {
}

func (x *UpdateRoleMenusRequest) Default() {
}

func (x *UpdateRoleMenusResponse) Default() {
}

func (x *GetRolesByUserRequest) Default() {
}

func (x *GetRolesByUserResponse) Default() {
}

func (x *RefreshPrivilegeDataRequest) Default() {
}

func (x *RefreshPrivilegeDataResponse) Default() {
}
